recipe: default.v1
language: en

pipeline:
- name: WhitespaceTokenizer
- name: custom_components.spell_checker.SpellCheckerComponent
- name: custom_components.emotion_analyzer.EmotionAnalyzer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: ResponseSelector
- name: FallbackClassifier

policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true

assistant_id: 20240627-224428-beveled-flag
